MyWatchList/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using MyWatchList.Data;
using MyWatchList.Models;
using MyWatchList.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyWatchList.Controllers
{
    public class DashboardController : Controller
    {
        private readonly MyWatchListContext _context;
        public Gebruiker gebruiker;
        public DashboardViewModel vm = new DashboardViewModel(); 

        public DashboardController(MyWatchListContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            vm = new DashboardViewModel();
            vm.GebruikerId = 1;
            return View(vm);
        }
    }
}

MyWatchList/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyWatchList.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MyWatchList.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyWatchList/Controllers/RegistrerenController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyWatchList.Data;
using MyWatchList.Models;
using MyWatchList.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyWatchList.Controllers
{
    public class RegistrerenController : Controller
    {
        private readonly MyWatchListContext _context;
        public List<Gebruiker> gebruikers;
        RegistrerenViewModel vm = new RegistrerenViewModel();
        public RegistrerenController(MyWatchListContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            vm = new RegistrerenViewModel();
            gebruikers = await _context.Gebruikers.ToListAsync();
            return View(vm);
        }

        public async Task<IActionResult> Registreren([Bind("Voornaam, Achternaam, Email, Geboortedatum, Wachtwoord")] Gebruiker gebruiker)
        {
            if (ModelState.IsValid && !gebruikers.Contains(gebruiker))
            {
                vm = new RegistrerenViewModel()
                {
                    Voornaam = gebruiker.Voornaam,
                    Achternaam = gebruiker.Achternaam,
                    Email = gebruiker.Email,
                    Geboortedatum = gebruiker.Geboortedatum,
                    Wachtwoord = gebruiker.Wachtwoord,
                    IsBeheerder = false,
                    Gebruiker = gebruiker,
            };
                _context.Add(gebruiker);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

MyWatchList/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Inloggen";
}

<h1>@ViewData["Title"]</h1>
<form>
    <div class="container kader">
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" />
            <small id="emailHelp" class="form-text text-muted">Typ hier uw email in.</small>
        </div>
        <div class="form-group">
            <label for="wachtwoord">Wachtwoord</label>
            <input type="password" class="form-control" id="password" />
            <small id="wachtwoordHelp" class="form-text text-muted">Typ hier uw wachtwoord in.</small>
        </div>
        <button type="submit" class="btn" id="login">Login</button>
        <button type="submit" class="btn" id="registreren" asp-controller="Registreren" asp-action="Index">Registreren</button>
        <div class="gastLogin">
            <a asp-controller="Dashboard" asp-action="Index">Ik wil als gast doorgaan ></a>
        </div>
    </div>
</form>