MyWatchList/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using MyWatchList.Data;
using MyWatchList.Models;
using MyWatchList.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyWatchList.Controllers
{
    public class DashboardController : Controller
    {
        private readonly MyWatchListContext _context;
        public Gebruiker gebruiker;
        public DashboardViewModel vm = new DashboardViewModel(); 

        public DashboardController(MyWatchListContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            vm = new DashboardViewModel();
            vm.GebruikerId = 1;
            return View(vm);
        }
    }
}

MyWatchList/Controllers/OverzichtSeriesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MyWatchList.ViewModels;
using MyWatchList.Models;
using MyWatchList.Data;
using Microsoft.EntityFrameworkCore;

namespace MyWatchList.Controllers
{
    public class OverzichtSeriesController : Controller
    {

        public List<Serie> series;
        private readonly MyWatchListContext _context;
        OverzichtSeriesListViewModel overzichtVM = new OverzichtSeriesListViewModel();
        SeriesDetailViewModel svm = new SeriesDetailViewModel();
        public Serie serie = new Serie();

        public async Task<IActionResult> Index()
        {
            series = await _context.Series.ToListAsync();
            overzichtVM.Series = series;
            return View(overzichtVM);
        }

        public OverzichtSeriesController(MyWatchListContext context)
        {
            series = new List<Serie>();
            _context = context;
        }

        public async Task<IActionResult> Search(OverzichtSeriesListViewModel viewModel)
        {
            series = await _context.Series.ToListAsync();
            if (!string.IsNullOrEmpty(viewModel.OverzichtSeriesSearch))
            {
                viewModel.Series = series.Where(x => x.Titel.ToLower().Contains(viewModel.OverzichtSeriesSearch.ToLower())).ToList();
            }
            else
            {
                viewModel.Series = series;
            }
            return View("Index", viewModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            svm.SerieId = id;
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                serie = await _context.Series.FindAsync(id);
                _context.Remove(serie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<IActionResult> Details(int? id)
        {
            serie = await _context.Series.FindAsync(id);
            serie.SpeeltIn = await _context.SpeeltIns.ToListAsync();
            List<Acteur> acteurs = await _context.Acteurs.ToListAsync();

            if (id == null)
            {
                return NotFound();
            }


            List<SpeeltIn> rollen = new List<SpeeltIn>();
            List<Acteur> acteursInSerie = new List<Acteur>();
            foreach (var rol in serie.SpeeltIn)
            {
                if (rol.SerieID == id)
                {
                    rollen.Add(rol);
                     int acteurId = rol.ActeurID;
                    foreach (var acteur in acteurs)
                    {
                        if (acteurId == acteur.ActeurID)
                        {
                            acteursInSerie.Add(acteur);
                        }
                    }
                }
            }
            if (serie == null)
            {
                return NotFound();
            }

            svm = new SeriesDetailViewModel()
            {
                Titel = serie.Titel,
                AantalSeizoenen = serie.AantalSeizoenen,
                MinimumLeeftijd = serie.MinimumLeeftijd,
                JaarVanUitkomst = serie.JaarVanUitkomst,
                Hoofdrollen = rollen,
                Acteurs = acteursInSerie,
                SerieId = id
            };

            return View(svm);
        }
    }
}

MyWatchList/Views/OverzichtSeries/Details.cshtml
@model MyWatchList.ViewModels.SeriesDetailViewModel
@{
    ViewData["Title"] = Model.Titel;
}
<div class="container">
    <div class="row">
        <div id="Terug" class=" linkTerug col-lg-12">
            <a asp-controller="OverzichtSeries" asp-action="Index">< Terug</a>
        </div>
        <div class="col-lg-4">
            <h1 class="dashboardHeader">@ViewData["Title"]</h1>
        </div>
    </div>
    <div class="row">
        <h5 class="col-lg-4">Jaar van uitkomst: @Model.JaarVanUitkomst</h5>
        <h5 class="col-lg-4">Aantal seizoenen: @Model.AantalSeizoenen</h5>
        <h5 class="col-lg-4">Minimum leeftijd: @Model.MinimumLeeftijd</h5>
    </div>
    <div class="row">
        <h5 class="col-lg-12">Cast</h5>
        <ul>
            @foreach (var acteur in Model.Acteurs)
            {
                string acteurNaam = acteur.Voornaam + " " + acteur.Achternaam;
                <li>@acteurNaam</li>
            }
        </ul>
    </div>
    <div class="col-lg-12">
        <a asp-controller="OverzichtSeries" asp-action="Delete" asp-route-id="@Model.SerieId">Serie verwijderen</a>
    </div>
</div>

MyWatchList/Views/OverzichtSeries/Index.cshtml
@model MyWatchList.ViewModels.OverzichtSeriesListViewModel

@{
    ViewData["Title"] = "Search";
}

<div class="container">
    <div class="row">
        <div id="Terug" class=" linkTerug col-lg-12">
            <a asp-controller="Dashboard" asp-action="Index">< Terug</a>
        </div>
        <form class="col-lg-12 row" asp-controller="OverzichtSeries" asp-action="Search" method="get">
            <div class="col-lg-4">
                <h1 class="dashboardHeader">@ViewData["Title"]</h1>
            </div>
            <div class="col-lg-4">
                <input asp-for="OverzichtSeriesSearch" class="form-control" />
            </div>
            <div class="col-lg-4">
                <input type="submit" value="Zoeken" class="btn" id="btnZoeken"/>
            </div>
        </form>
        <div class="col-lg-12" id="searchResults">
            @{
                if (Model.Series != null)
                {
                    foreach (var serie in Model.Series)
                    {
                        <div class="col-lg-12 searchItem card">
                            <div class="card-body">
                                <h5>@serie.Titel</h5>
                                <h6 class="card-subtitle mb-2 text-muted">@serie.JaarVanUitkomst</h6>
                                <p class="card-text">Seizoenen: @serie.AantalSeizoenen</p>
                                <p><a asp-controller="OverzichtSeries" asp-action="Details" asp-route-id="@serie.SerieID" class="card-link">Details</a></p>
                            </div>
                        </div>
                    }
                }
            }
        </div>
    </div>
</div>